apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: runInHost
spec:
  privileged: true
  hostPID: true
 # The rest fills in some required fields you can override.
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
