---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runInHost
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - runInHost


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: runInHost
roleRef:
  kind: ClusterRole
  name: runInHost
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: runInHost
  namespace: default
